services:
  n8n:
    image: docker.n8n.io/n8nio/n8n
    container_name: n8n_core
    restart: unless-stopped
    ports:
      - "5678:5678"
    environment:
      - N8N_COMMUNITY_PACKAGES_ENABLED=true
      - N8N_REINSTALL_MISSING_PACKAGES=true
    env_file:
      - ../.env
    volumes:
      - ../n8n_data:/home/node/.n8n

  telegram_listener:
    build:
      context: ..
      dockerfile: deploy/listener.Dockerfile
    container_name: veloce_listener
    restart: unless-stopped
    depends_on:
      - n8n
    env_file:
      - ../.env
    volumes:
      - ..:/app
