services:
  orchestrator:
    build:
      context: ..
      dockerfile: deploy/orchestrator.Dockerfile
    container_name: veloce_orchestrator
    restart: unless-stopped
    ports:
      - "8000:8000"
    env_file:
      - ../.env
    volumes:
      - ..:/app

  telegram_listener:
    build:
      context: ..
      dockerfile: deploy/listener.Dockerfile
    container_name: veloce_listener
    restart: unless-stopped
    depends_on:
      - orchestrator
    env_file:
      - ../.env
    volumes:
      - ..:/app
