services:
  orchestrator:
    build:
      context: ..
      dockerfile: deploy/orchestrator.Dockerfile
    container_name: veloce_orchestrator
    restart: unless-stopped
    ports:
      - "8000:8000"
    env_file:
      - ../.env
    volumes:
      - ..:/app
    environment:
      TZ: Asia/Kuala_Lumpur

  telegram_listener:
    build:
      context: ..
      dockerfile: deploy/listener.Dockerfile
    container_name: veloce_listener
    restart: on-failure:5
    depends_on:
      - orchestrator
    env_file:
      - ../.env
    environment:
      VELOCE_ORCHESTRATOR_URL: http://orchestrator:8000/veloce-task-scheduler
      TZ: Asia/Kuala_Lumpur
    volumes:
      - ..:/app
